apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchLabels:
      jmx: prometheus-service
  enableAdminAPI: false
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: addi-prom.yaml