apiVersion: v1
kind: Service
metadata:
  name: threadmonitor-svc
  namespace: monitoring
spec:
  ports:
    - name: http
      targetPort: 9090
      port: 9090
      protocol: TCP
  selector:
    prometheus: prometheus